export enum EActionAssistant {
  SET_LOADING = 'SET_LOADING',
  GET_SUGGEST_IDEAS = 'GET_SUGGEST_IDEAS',
  GET_DATA_CONVERSATION = 'GET_DATA_CONVERSATION',
  CLEAR_DATA_CONVERSATION = 'CLEAR_DATA_CONVERSATION',
  GET_HISTORY_CONVERSATION = 'GET_HISTORY_CONVERSATION',
  HIDE_SUMMARIZE_IDEA = 'HIDE_SUMMARIZE_IDEA',
  GENERATE_RESPONSE = 'GENERATE_RESPONSE'
}
